inherit_from: ./.rubocop.enabled.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals

Style/DotPosition:
  EnforcedStyle: trailing

Style/FormatString:
  EnforcedStyle: percent

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
