addons:
  postgresql: 9.6
dist: trusty
language: ruby
cache:
  bundler: true
  directories:
  - client/node_modules
  - "/home/travis/.rvm/"
before_script:
  - bundle exec rails db:create RAILS_ENV=test
test:
  adapter: postgresql
  database: string-sync_test
  username: postgres
rvm:
  - 2.3.1
script:
  - bundle exec rails test
  - cd client && npm install && npm run test && cd ..
env:
  secure: hCKigEL/b7K2Njpt09+ZEdCrildVhBSXOFvv5vJwPOTHOoC72vQnljyuTK6No3XXetS8zP4+sesCV0yoUZaqGZqFeV/aSpPqtrtVFi6j2p+x3kYGUJu8m9NQ/vdhWXd/hYO2dntKh8iONSmhIE9Cn7Lehuuok45vN+tcwSpG9c6Vz8+BN2i9l/N4P6z70Q7qfDjA+C0kt7G/3SDiFxXZrmD1Wz2f5sC64jBps6S8YU2kZXmzDYPTvqAgw82Ux3YAwheFt6iS7FEu/KiYp1Umc1CptxcD70K498u6xIY5Xv+cXbTyf9CATO4MmCBtFCERkAVEDBFOqMc3Ghkz26lEO5COyR8JoI3NTTbfzeDcCiKLwUuAdK0+P6po21ZTtKe3JdfXox8dhQAh0r4FM4FsiKrqd8XeRsrrQrdzTWx1xfTLpuF477ErMqJbNHL3Qf3qdyWKXaMq9HEWgSWuGa8TpjQEv7wAF4IT2dQOLGNTyNEleSsMQ7KxUJzPkQEFaQMB9+HjOe6P7+g6aqwbSoN9ezGIMeMIVToB/9HO65st2demel47kXHYFus3MViKWAG5uNkR3OTlAV0IVpF817D7KDwKXdffEEN02qLoh9daQkFrxAwqALwEA2lXrhwFcdv4nsaLnQquVjpr27z5mTH9s8OO5fpp8/tj0t3WPY2tEtk=
deploy:
  provider: heroku
  app: string-sync-beta
  api_key:
    secure: xxYyIVaZ4t+g8n4889knjDLswsTx8VttOVIHrzPftUZ6EBVJJyhyr4rB0t47Gi5QbzzW1eJ4awFIpaVeJ3wvNhCmwTP+xlHxpefd5TUhPz5IhO/YsZZvcz3p8ELMaNp826C3tXw2qqTkRISDXDf9se5hJ5JJxygIo786cNvFNgBIvRcVmuct6aKUGAnVZWUK/BnrRTdQH93KEZEqutILc8ywPT4K14xnMadLtlC4F+nH8lFpOlo/TWFQmDaufswdV6ph8thet82Qi7tl4tgoIdqAV+s05a4EbpWCpT/5rAskYQx8mNLG3bRGOLBl5D+uGCkP67noeo+XUZIj2m3+Xi73U/tAaKfU02giUqAa2w8yTwsNu7+dj8d9qfZEobuhH7x5d895qVELLLVp5NxXEV07pKzhZ3a5bNd4zU/8dzp9zJbTvNQOwjKrqB+g5il7oZLaCT1Ak6ok90gshiQY+bApfLkBeEl3o0BsxbpqPSOfAJov6JALnwBymqi2RQOwvYReM4LYO+1hteaZTnSrsX5wJaXh//CPUN4s5rgSNW5fgAKNr7wyWS1zJJvhMX5i1ykQaZ6nZmzf+DZEyfMcwkJ3bG7shLY0rNn+Gho7ZjN3cvSSD1Zk50L2k2ydHMvzOgoZN19jBrFnFh55bvGEU6wb7IO+A7uX7g9tcp/u40s=
