addons:
  postgresql: 9.6
dist: trusty
language: ruby
cache:
  bundler: true
before_script:
  - bundle exec rails db:create RAILS_ENV=test
test:
  adapter: postgresql
  database: string-sync_test
  username: postgres
rvm:
  - 2.6.0
script:
  - bundle exec rails test
  - cd client && npm install && cd .. && npm run test
env:
  global:
    secure: kUheTymsuegxDA2ybuhg6bBN2A+zxk8ScbKrPZ/khTjeZfjnBsLK94A/NOpbCRsSsutRraKczd3zjFGwFIZKbIRoVpF+1s1JhOC56FCC9RLDHJ1yMeNM02QKR7+a66F5M4euGklpzFzMY1DJehrXLD7XlPm2nq2RducNWER3MVtes3gdk52/t5QLt6ukd9Oj2H2hSUBefDF+IHab8C4iUc1tiXDSjbIJffBVFyvOcNFLp5cckIHVfHO2pku1skBRune424R+S/r2Kc8nUcSn2Wr36Ce1Gds8ZvDnU45mfy7rik0W+sxU9PtZ40qWj5d70+p0eHlpQ8jYmwVS00AgcY4vLT4aNpWbJV5qjdDWthJVftOErJHz7uVsIHMYkBLsDfEYvDPgePP2IU5CG+RrhoFQA964taxB0Eokry7eOHADloeztf9yz3uV1XI7YIfwO6jIG7ODRHq9OmMDNxk1U0qAusI4LceR2sz5K9BeM7J+0l6JBXUcI9+S/EYrMiPi15tK98x8tuSWG3vhn48dHj4uCUMcMm/AKv0l1Ky/Klu0hrg384Q3GYcWxfKC//djdYCg/JwMWPwQ9W/DPgJkdXK84QLvK6ef9JIcu025B+FzRERfu3rSkD8THDmrU61HzDmEYZdPR4j4tEYpXKoHfwMyfdPRW74ej6nIwLt1GrE=
deploy:
  on:
    repo: jaredjj3/string-sync
    branch: master
  provider: heroku
  app: string-sync
  api_key:
    secure: sIPKhVrElJ1h/RiTbIxwmnkYEguLw5G13v+rQvMS+vgUxtCXhftpdToyyj3t9o0AWnJh1HOg891L+hdSk18s+BaQJGpkFlU9p9oDoaKWvfmSWM1pJ3mD7G2jK/sQmUevfy+NbFqftTFR2eB9eLmk08FSXBibhQr+sORQCXQydw9NAs/MNDBzpRASlOvMuCfWo3i9dPbrejPfxY0Qmreyfm7eyhPtQI7y3HGH7Pyr4IlIIBD86wvgJOcdacqAGWYSx6gi8iuq7QUzlbV3bkFo9nRGoVpPnLNOOYgjC03J9DPdf4FHqnUnSgkt09G5ozSeIJbkMEf217CSgaSwvkfuFh8IDhmmWd/bcn1WJJTFfpG5mgsfjNGFmlL6UroemzqMvrgNR88XzvvWI9b9/5HQDQ1U6Ob4WNA/t765Wo7coNvBwdZWdouqui6woV2LkEsejYsqygUaj8/Kjm0DdbLTzJRWi6bxtBvUcaQ0aCfC8gJ70ocZBbu/vk9qSCLP8IkeDS5C+J6JgAfD9SrJYdnuKTSukhqAtzna8R+SRFUXqgv6nVOAjl01eJuY/EsiGVTOc/cMygEVPGVJbE4Oa5pjljFeGKk5NA8HrEiz5arkde83EG0tCfEKjV9kU5W1bL4Ua5TyPr4YIiUJ2Mn0/UCCERXy9Xfk0OgTexX0p16Eruw=
