version: 0.2

phases:
  install:
    commands:
      - echo Installing script node_modules...
      - (cd ./bin/scripts && yarn install)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Cleaning up previous builds
      - ./bin/ss down server
      - ./bin/ss down web

  build:
    commands:
      - echo Building images...
      - ./bin/ss build server
      - ./bin/ss build web
      - echo Testing images...
      - ./bin/ss test server
      - ./bin/ss test web

  post_build:
    commands:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]
        then
          echo Pushing server images...
          docker tag ss-server $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
        else
          echo Build failed, skipping post_build step...
        fi

cache:
  paths:
    - bin/scripts/node_modules/**/*

artifacts:
  files: "**/*"
