version: 0.2

phases:
  install:
    commands:
      - echo Installing script node_modules...
      - (cd ./bin/scripts && yarn install)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - ./bin/ss down server
  build:
    commands:
      - echo Build started on `date`
      - ./bin/ss build server
      - docker tag ss-server $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - ./bin/ss test server

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

cache:
  paths:
    - ./bin/scripts/node_modules/**/*
