version: 0.2

phases:
  install:
    commands:
      - ./bin/codebuild/install

  pre_build:
    commands:
      - ./bin/codebuild/pre_build
    finally:
      - ./bin/codebuild/pre_build_finally

  build:
    commands:
      - ./bin/codebuild/build
    finally:
      - ./bin/codebuild/build_finally

  post_build:
    commands:
      - ./bin/codebuild/post_build
    finally:
      - ./bin/codebuild/post_build_finally

cache:
  paths:
    - /root/.yarn/**/*

reports:
  jest_reports:
    files:
      - junit.web.xml
      - junit.api.xml
    file-format: JUNITXML
    base-directory: reports

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    BuildImageDefinitionsOutput:
      name: BuildImageDefinitionsOutput
      base-directory: imagedefinitions-artifacts
      files:
        - '**/*'
    BuildWebOutput:
      name: BuildWebOutput
      base-directory: web-artifacts
      files:
        - '**/*'
