version: 0.2

phases:
  install:
    commands:
      - echo Installing script node_modules...
      - (cd ./bin/scripts && yarn install)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Cleaning up previous builds
      - ./bin/ss down api

  build:
    commands:
      - echo Logging into docker...
      - aws s3 cp s3://$S3_SECRETS_BUCKET/.docker.key .docker.key
      - docker login -u stringsync --password-stdin < .docker.key
      - rm .docker.key
      - echo Building images...
      - ./bin/ss build -pd
      - echo Testing images...
      # - ./bin/ss test api
      # - ./bin/ss test web

  post_build:
    commands:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]
        then
          echo Pushing server images...
          docker tag stringsync $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

          echo Writing imagedefinitions.json...
          IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
          printf '[{"name":"api","imageUri":"'$IMAGE_URI'"}]' > imagedefinitions.api.json
          printf '[{"name":"worker","imageUri":"'$IMAGE_URI'"}]' > imagedefinitions.worker.json

          echo Adding REACT_APP_SERVER_URI to .env
          echo REACT_APP_SERVER_URI=$REACT_APP_SERVER_URI >> packages/web/.env

          echo Building web project...
          (yarn web install && yarn web build)

          echo Moving everything into root build dir...
          mkdir deploy
          mv imagedefinitions.api.json deploy
          mv imagedefinitions.worker.json deploy
          mv packages/web/build/* deploy
        else
          echo Build failed, skipping post_build step...
        fi

        echo Logging out of docker...
        docker logout

cache:
  paths:
    # - bin/scripts/node_modules/**/*
    # - node_modules/**/*

artifacts:
  base-directory: deploy
  files:
    - '**/*'
