version: 0.2

phases:
  install:
    commands:
      - echo Installing script node_modules...
      - (cd ./bin/scripts && yarn install)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ss-server ./server
      - docker tag ss-server $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      # - echo checking ctx
      # - ./bin/ss test server -d ctx
      - echo checking data-loaders
      - ./bin/ss test server -d data-loaders
      - echo checking db
      - ./bin/ss test server -d db
      - echo checking guards
      - ./bin/ss test server -d guards
      - echo checking jobs
      - ./bin/ss test server -d jobs
      - echo checking mail
      - ./bin/ss test server -d mail
      - echo checking password
      - ./bin/ss test server -d password
      - echo checking redis
      - ./bin/ss test server -d redis
      - echo checking resolvers
      - ./bin/ss test server -d resolvers
      - echo checking server
      - ./bin/ss test server -d server
      - echo checking user-session
      - ./bin/ss test server -d user-session
      - echo checking util
      - ./bin/ss test server -d util

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

cache:
  paths:
    - ./bin/scripts/node_modules/**/*
