version: "3.7"

services:
  server:
    build:
      context: ./server
    depends_on:
      - transpiler
    volumes:
      - ./server:/server
      - /server/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    command: ["yarn", "dev"]

  transpiler:
    build:
      context: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    command: ["yarn", "watch"]
