version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    depends_on:
      - transpiler
    volumes:
      - server-build:/server/build
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    command: ["yarn", "dev"]

  transpiler:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - server-build:/server/build
      - ./server:/server
      - /server/node_modules
    command: ["yarn", "watch"]

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  server-build:
  postgres:
