version: '3.7'

services:
  web:
    image: ss-web:latest
    build:
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - ./web/src:/web/src
      - ./web/public:/web/public
    environment:
      NODE_ENV: test
      REACT_APP_SERVER_URI: ''
