version: '3.7'

services:
  web:
    container_name: ss_test_web
    image: ss-web:latest
    build:
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - ./common:/string-sync/common
      - ./web/src:/string-sync/web/src
      - ./web/public:/string-sync/web/public
    environment:
      NODE_ENV: test
      REACT_APP_SERVER_URI: ''
