version: "3.7"

services:
  test:
    image: stringsync:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: test
      REACT_APP_SERVER_URI: fake_app_server_uri
      REACT_APP_GRAPHQL_ENDPOINT: /graphql
    volumes:
      - ./packages:/stringsync/packages
