version: "3.7"

services:
  server:
    build:
      context: ./server
    depends_on:
      - transpiler
    volumes:
      - server-build:/server/build
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    command: ["yarn", "dev"]

  transpiler:
    build:
      context: ./server
    volumes:
      - server-build:/server/build
    command: ["yarn", "watch"]

volumes:
  server-build:
