version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  server:
    image: ss-server:latest
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: test
      PORT: 3000
      WEB_URI: ''
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./common:/string-sync/common
      - ./server/src:/string-sync/server/src
    links:
      - db
