version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    image: redis:5.0

  server:
    image: ss-server:latest
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      ROLE: server
      NODE_ENV: development
      PORT: 3000
      WEB_URI: http://web:8080
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./server/src:/server/src
    links:
      - db
      - redis
    depends_on:
      - migrater
    command: ['yarn', 'start']

  worker:
    image: ss-server:latest
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      ROLE: worker
      NODE_ENV: development
      PORT: 3001
      WEB_URI: http://web:8080
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./server/src:/server/src
    links:
      - db
      - redis
    depends_on:
      - migrater
    command: ['yarn', 'start']

  migrater:
    container_name: migrater
    image: ss-server:latest
    environment:
      NODE_ENV: development
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./server/src:/server/src
    links:
      - db
    command: ['yarn', 'migrate']

  web:
    image: ss-web:latest
    build:
      context: ./web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: test
      REACT_APP_SERVER_URI: http://server:3000/graphql
    volumes:
      - ./web/src:/web/src
      - ./web/public:/web/public
    links:
      - server
    command: ['yarn', 'start']

  e2e:
    image: ss-e2e:latest
    shm_size: '1g'
    build:
      context: ./e2e
      dockerfile: ./Dockerfile
    volumes:
      - ./e2e/src:/e2e/src
    environment:
      WEB_URI: http://web:8080
    links:
      - server
      - web
