version: "3.7"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/src:/app/src
      - ./server/db:/app/db
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: host.docker.internal
    links:
      - db

    ports:
      - "3000:3000"
    command: ["yarn", "build:dev"]

  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    links:
      - server
    command: ["yarn", "start"]

volumes:
  postgres:
