version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - server-build:/app/build
      - ./server/prisma:/app/prisma
      - ./server/graphql:/app/graphql
    environment:
      NODE_ENV: development
      PRISMA_SECRET: mysecret123
    ports:
      - "8080:8080"
    links:
      - prisma
    command: ["yarn", "dev"]

  transpiler:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - server-build:/app/build
      - ./server:/app
      - /app/node_modules
    command: ["yarn", "watch"]

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            user: postgres
            password: postgres
            rawAccess: true
            port: 5432
            migrations: true

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  server-build:
  postgres:
