version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    container_name: redis
    image: redis:5.0

  app:
    container_name: app
    image: stringsyncapi:dev
    build:
      context: ./api
    env_file:
      - env/dev.env
      - env/secrets.env
    volumes:
      - ./api/src:/api/src
    links:
      - db
      - redis
    ports:
      - '3000:3000'
    entrypoint: ['./bin/wait-for-it.sh', 'db:5432', '--']
    command: >
      bash -c "yarn migrate && yarn seed && pm2-runtime ecosystem.dev.config.js"

  web:
    container_name: web
    image: stringsyncweb:dev
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/web/src
    links:
      - app
    ports:
      - '8080:3000'
    command: ['yarn', 'start']
