version: "3.7"

services:
  test:
    image: stringsync:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - env/web.test.env
    volumes:
      - ./packages:/stringsync/packages
