version: "3.7"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            user: postgres
            password: postgres
            rawAccess: true
            port: 5432
            migrations: true

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    environment:
      NODE_ENV: development
      PRISMA_SECRET: mysecret123
      JWT_SECRET: mysecret123
    ports:
      - "3000:3000"
    command: ["yarn", "build:dev"]

  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    links:
      - server
    command: ["yarn", "start"]

volumes:
  postgres:
