version: '3.7'

services:
  test-db:
    container_name: ss_test_db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    networks:
      - test-network

  test-server:
    container_name: ss_test_server
    image: ss-server:latest
    build:
      context: ./server
      dockerfile: ./dev.Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      CLIENT_URI: http://localhost:8080
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: test-db
      DB_PORT: 5432
    volumes:
      - type: bind
        source: ./common
        target: /string-sync/common
      - type: bind
        source: ./server/src
        target: /string-sync/server/src
    links:
      - test-db
    depends_on:
      - test-db
    ports:
      - '3000:3000'
    networks:
      - test-network

networks:
  test-network:
    name: ss_test_network
