version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    container_name: redis
    image: redis:5.0

  migrate:
    container_name: migrate
    image: stringsync:latest
    env_file:
      - env/dev.env
      - env/secrets.env
    volumes:
      - ./api/src:/app/api/src
    links:
      - db
    entrypoint: ['/app/api/bin/wait-for-it.sh', 'db:5432', '--']
    command: 'bash -c "yarn migrate && yarn seed"'

  app:
    container_name: app
    image: stringsync:latest
    env_file:
      - env/dev.env
      - env/secrets.env
    volumes:
      - ./api/src:/app/api/src
    links:
      - db
      - redis
    ports:
      - '3000:3000'
    command: ['yarn', 'dev:api']

  worker:
    container_name: worker
    image: stringsync:latest
    env_file:
      - env/dev.env
      - env/secrets.env
    volumes:
      - ./api/src:/app/api/src
    links:
      - db
      - redis
    command: ['yarn', 'dev:worker']

  web:
    container_name: web
    image: stringsync:latest
    volumes:
      - ./web/src:/app/web/src
    links:
      - app
    command: ['yarn', 'dev:web']
