version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    container_name: redis
    image: redis:5.0

  migrate:
    container_name: migrate
    image: stringsync:prod
    build:
      context: .
    env_file:
      - env/fakeprod.env
      - env/secrets.env
    links:
      - db
    entrypoint: ['./api/bin/wait-for-it.sh', 'db:5432', '--']
    command: 'bash -c "cd api && yarn migrate && yarn seed"'

  app:
    container_name: app
    image: stringsync:prod
    build:
      context: .
    env_file:
      - env/fakeprod.env
      - env/secrets.env
    links:
      - db
      - redis
    ports:
      - '3000:3000'
    command: ['node', '/app/api/build/entrypoints/api.js']

  worker:
    container_name: worker
    image: stringsync:prod
    build:
      context: .
    env_file:
      - env/fakeprod.env
      - env/secrets.env
    environment:
      NODE_ENV: production
    links:
      - db
      - redis
    command: ['node', '/app/api/build/entrypoints/worker.js']
