version: '3.7'

services:
  db:
    container_name: ss_db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    container_name: ss_server
    image: ss-server:latest
    build:
      context: ./server
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./common:/string-sync/common
      - ./server/src:/string-sync/server/src
      - ./server/db:/string-sync/server/db
      - /string-sync/node_modules
      - /string-sync/server/node_modules
    environment:
      CLIENT_URI: http://localhost:8080
      NODE_ENV: development
      JWT_SECRET: stringsync
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: host.docker.internal
    links:
      - db
    ports:
      - '3000:3000'
    command: ['yarn', 'build:dev']

  web:
    container_name: ss_web
    image: ss-web:latest
    build:
      context: ./web
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./common:/string-sync/common
      - ./web/src:/string-sync/web/src
      - ./web/public:/string-sync/web/public
      - /string-sync/node_modules
      - /string-sync/web/node_modules
    environment:
      NODE_ENV: development
    ports:
      - '8080:8080'
    links:
      - server
    command: ['yarn', 'start']

volumes:
  postgres:
  common:
