version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    container_name: redis
    image: redis:5.0

  app:
    container_name: app
    image: stringsync:prod
    build:
      context: .
    env_file:
      - env/dev.env
      - env/secrets.env
    links:
      - db
      - redis
    ports:
      - '3000:3000'
    entrypoint: ['/app/api/bin/wait-for-it.sh', 'db:5432', '--']
    command: ['node', '/app/api/build/entrypoints/api.js']
