version: "3.7"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    image: redis:5.0

  graphql:
    image: stringsync:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: secrets.env
    environment:
      NODE_ENV: development
      PORT: 3000
      WEB_URI: http://localhost:8080
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
      LOG_LEVEL: info
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_SECRET: keyboardcat
      S3_BUCKET: stringsync-dev
      S3_VIDEO_SRC_BUCKET: ss-vids-dev-source-p35827dydqh3
      CLOUDFRONT_DOMAIN_NAME: d2yt8e0its832a.cloudfront.net
      VIDEO_MESSAGE_QUEUE_NAME: ss-vids-dev
    volumes:
      - ./packages:/stringsync/packages
    links:
      - db
      - redis
    ports:
      - "3000:3000"
    command: ["yarn", "dev:graphql"]

  jobs:
    image: stringsync:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: secrets.env
    environment:
      NODE_ENV: development
      PORT: 3000
      WEB_URI: http://localhost:8080
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
      LOG_LEVEL: info
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_SECRET: keyboardcat
      S3_BUCKET: stringsync-dev
      S3_VIDEO_SRC_BUCKET: ss-vids-dev-source-p35827dydqh3
      CLOUDFRONT_DOMAIN_NAME: d2yt8e0its832a.cloudfront.net
      VIDEO_MESSAGE_QUEUE_NAME: ss-vids-dev
    volumes:
      - ./packages:/stringsync/packages
    links:
      - db
      - redis
    command: ["yarn", "dev:jobs"]