version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/src:/app/src
      - ./server/tests:/app/tests
      - /app/node_modules
    environment:
      NODE_ENV: test
    command: ['yarn', 'test:unit']

  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      NODE_ENV: test
    command: ['yarn', 'test:unit']
