version: "3.7"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    environment:
      NODE_ENV: development
      PRISMA_SECRET: mysecret123
      JWT_SECRET: mysecret123
    ports:
      - "4000:4000"
    command: ["yarn", "build:dev"]

  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    links:
      - server
    command: ["yarn", "start"]

volumes:
  postgres:
