version: "3.7"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    image: redis:5.0

  graphql:
    image: stringsync:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      WEB_URI: http://localhost:8080
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_SECRET: keyboardcat
    volumes:
      - ./modules:/stringsync/modules
    links:
      - db
      - redis
    ports:
      - "3000:3000"
    command: ["yarn", "dev"]

  migrate:
    image: stringsync:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./modules:/stringsync/modules
    links:
      - db
    command: ["yarn", "dev:migrate"]
