# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9022bc9a08d18aeb3af019459b9aee4103ba61f91b6a8eba92fe25ead8f5ee8f62ac054ee55e3b438ecc2e03b861a49b1c94df6a8fb0f408d9d2317d1cc759fa
  s3_bucket: <%= Figaro.env.s3_bucket! %>
  s3_region: <%= Figaro.env.s3_region! %>
  s3_access_key_id:  <%= Figaro.env.s3_access_key_id! %>
  s3_secret_access_key:  <%= Figaro.env.s3_secret_access_key! %>
  facebook_api_id: <%= Figaro.env.facebook_api_id! %>
  facebook_secret: <%= Figaro.env.facebook_secret! %>
  google_client_id: <%= Figaro.env.google_client_id! %>
  google_secret: <%= Figaro.env.google_secret! %>

test:
  secret_key_base: 854958871ca978d6c114eb63d5d7996028081610276f2ad2540eb1f2d0e5ffe49bd60e5b6082693dde636297a45bcd67cf920c81e45d5ecb5dfe0d325b9cb366
  s3_bucket: <%= Figaro.env.s3_bucket! %>
  s3_region: <%= Figaro.env.s3_region! %>
  s3_access_key_id:  <%= Figaro.env.s3_access_key_id! %>
  s3_secret_access_key:  <%= Figaro.env.s3_secret_access_key! %>
  facebook_api_id: <%= Figaro.env.facebook_api_id! %>
  facebook_secret: <%= Figaro.env.facebook_secret! %>
  google_client_id: <%= Figaro.env.google_client_id! %>
  google_secret: <%= Figaro.env.google_secret! %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket: <%= Figaro.env.s3_bucket! %>
  s3_region: <%= Figaro.env.s3_region! %>
  s3_access_key_id:  <%= Figaro.env.s3_access_key_id! %>
  s3_secret_access_key:  <%= Figaro.env.s3_secret_access_key! %>
  facebook_api_id: <%= Figaro.env.facebook_api_id! %>
  facebook_secret: <%= Figaro.env.facebook_secret! %>
  google_client_id: <%= Figaro.env.google_client_id! %>
  google_secret: <%= Figaro.env.google_secret! %>