AWSTemplateFormatVersion: 2010-09-09
Description: A stack for deploying StringSync in AWS

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://stringsync-cf-templates.s3.amazonaws.com/{{STRINGSYNC_DIR_STRING}}/network.yml
