version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis1:
    container_name: redis1
    image: redis:5.0

  redis2:
    container_name: redis2
    image: redis:5.0

  redis3:
    container_name: redis3
    image: redis:5.0

  test:
    container_name: test
    image: stringsync:latest
    env_file:
      - ../env/api.test.env
    volumes:
      - ./src:/api/src
      - ./reports:/api/reports
    links:
      - db
      - redis1
      - redis2
      - redis3
    entrypoint: ['./bin/wait-for-it.sh', 'db:5432', '--']
