version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    image: redis:5.0

  app:
    image: stringsync:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ../../env/dev.env
      - ../../env/secrets.env
    volumes:
      - ./src:/app/src
    links:
      - db
      - redis
    ports:
      - '3000:3000'
    command: ['pm2', 'start', 'ecosystem.config.js', '--no-daemon']
